### ISSUE TITLE
Ajouter CR au blog

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/ouvroir.github.io#40]
- [x] normaliser le yaml requis
- [x] ajouter les CR aux actualités
- [x] ajouter les tags des CR
- [x] mise à jour du slugmap
- [x] ajuster BlogPost et BlogPostPreview pour les CR
- [x] modifier les pages d'accueil pour montrer seulement les 3 dernières actualités

**Comment by lenaMK** [comment]
yaml proposé: 
```yaml
title: Réunion de laboratoire 
description: Compte-rendu de la réunion hebdomadaire du 18 janvier 2022
author: ouvroir
date: 2022-01-01
tags: 
  - cr
  - ouvroir

```
